a = float(input("Digite a primeira nota: "))
b = float(input("Digite a segunda nota: "))
c = float(input("Digite a terceira nota: "))
d = float(input("Digite a quarta nota: "))
print("A média aritmética é", (a+b+c+d)/4)
